/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
#define ORYX_CONFIGURATOR

// TODO these initial configs (generated by oryx configurator)
#define USB_SUSPEND_WAKEUP_DELAY 0
#define FIRMWARE_VERSION u8"30zwA/JpPP7"


//*****************************************************************************
//* Auto Shift
//* rules.mk: AUTO_SHIFT_ENABLE = yes
//*****************************************************************************

// Time after which the shifted version of the key is emitted. Default: 175ms
#define AUTO_SHIFT_TIMEOUT 165

// For more granular control together with get_autoshift_timeout:
// #define AUTO_SHIFT_TIMEOUT_PER_KEY

// Holding the key repeats shifted key. Tap and hold within TAPPING_TERM to repeat the normal key. Default: disabled
// #define AUTO_SHIFT_REPEAT
// #define AUTO_SHIFT_NO_AUTO_REPEAT

// Fine grained control for AUTO_SHIFT_REPEAT together with get_auto_shift_repeat() and get_auto_shift_no_auto_repeat().
// #define AUTO_SHIFT_REPEAT_PER_KEY
// #define AUTO_SHIFT_NO_AUTO_REPEAT_PER_KEY

// Enable auto shift for key press accopmanied by other modifiers (e.g. CTRL+A). Default: disabled
#define AUTO_SHIFT_MODIFIERS

// Do not Auto Shift special keys, which include -_, =+, [{, ]}, ;:, ‘“, ,<, .>, and /?
#define NO_AUTO_SHIFT_SPECIAL

// Do not Auto Shift numeric keys, zero through nine.
#define NO_AUTO_SHIFT_NUMERIC

#define NO_AUTO_SHIFT_ALPHA

//*****************************************************************************
//* Tap-Hold Configuration Options
//*****************************************************************************
// TODO: check config
// Time after which a key press is regarded as a hold. Default: 200ms
#define TAPPING_TERM 300

// For more granular control with get_tapping_term:
// #define TAPPING_TERM_PER_KEY

// Immediately select the hold action when another key is tapped (pressed and then released)
// Can also affect Mod Tap (reduce delay or with IGNORE_MOD_TAP_INTERRUPT).
#define PERMISSIVE_HOLD

// Immediately select the hold action when another key is pressed
// Can also affect Mod Tap (reduce delay or with IGNORE_MOD_TAP_INTERRUPT).
// #define HOLD_ON_OTHER_KEY_PRESS

// Mod Tap keys are no longer treated as a special case, and their behavior will match the behavior of other dual-role keys
#define IGNORE_MOD_TAP_INTERRUPT

// Removes the ability to repeate the normal key after a hold after tap combination and activates the hold instead.
// #define TAPPING_FORCE_HOLD

// Releasing a hold key without another key pressed results in the normal key emitted instead of ignoring it.
// #define RETRO_TAP

// Enables the special keys to configure the TAPPING_TERM from the keyboard:
// rules.mk: DYNAMIC_TAPPING_TERM_ENABLE = yes

//*****************************************************************************
//* RGB Matrix Configuration Options
//*****************************************************************************
// TODO
//#undef RGB_DISABLE_TIMEOUT
#define RGB_DISABLE_TIMEOUT 600000      // (10 min) number of milliseconds to wait until rgb automatically turns off (Default: 0)
#define RGB_MATRIX_STARTUP_SPD 60       // sets the default animation speed, if none has been set (Default: 127)
// #define RGB_MATRIX_LED_PROCESS_LIMIT 9  // limits the number of LEDs to process in an animation per task run (increases keyboard responsiveness) (Default: (DRIVER_LED_TOTAL + 4) / 5)
// #define RGB_MATRIX_LED_FLUSH_LIMIT 16   // limits in milliseconds how frequently an animation will update the LEDs. 16ms (default) is equivalent to limiting to 60fps (increases keyboard responsiveness)

// Layer TT()
#define TAPPING_TOGGLE 1
