/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
#define ORYX_CONFIGURATOR

// TODO these initial configs (generated by oryx configurator)
#define USB_SUSPEND_WAKEUP_DELAY 0
#define FIRMWARE_VERSION u8"30zwA/JpPP7"


//*****************************************************************************
//* Tap-Hold Configuration Options
//*****************************************************************************
// Time after which a key press is regarded as a hold. Default: 200ms
#define TAPPING_TERM 150

#define IGNORE_MOD_TAP_INTERRUPT

//*****************************************************************************
//* One-Shot-Modifier Configuration Options
//*****************************************************************************
#define ONESHOT_TAP_TOGGLE 3  /* Tapping this number of times holds the key until tapped once again. */
#define ONESHOT_TIMEOUT 3000  /* Time (in ms) before the one shot key is released */

//*****************************************************************************
//* RGB Matrix Configuration Options
//*****************************************************************************
#undef RGB_DISABLE_TIMEOUT
#define RGB_DISABLE_TIMEOUT 300000      // (5 min) number of milliseconds to wait until rgb automatically turns off (Default: 0)
#define LAYER_STATE_16BIT
#define RGB_MATRIX_STARTUP_SPD 60
